steps:
# Build and tag using commit sha
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'https://github.com/make-dot-tech/sqlpad.git/$PROJECT_ID/sqlpad-image:${SHORT_SHA}', '-f', 'Dockerfile']
# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'https://github.com/make-dot-tech/sqlpad.git/$PROJECT_ID/sqlpad-image:${SHORT_SHA}']
# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "sqlpad-pipeline",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "sqlpad-image=https://github.com/make-dot-tech/sqlpad.git/$PROJECT_ID/sqlpad-image:${SHORT_SHA}"
    ]
