apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlpad-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlpad-app
        env: development
    spec:
      containers:
      - name: sqlpad-app
        image: gcr.io/[PROJECT_ID]/sqlpad:v1
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: my-sqlpad-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: my-sqlpad
