apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlpad-deployment
spec:
  selector:
    matchLabels:
      app: sqlpad-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlpad-app
        env: development
    spec:
      containers:
      - name: sqlpad-app
        image: gcr.io/alphastack-sandbox/github.com/make-dot-tech/sqlpad@sha256:2dd70062ac38573d4d43f6e94b309c6a32a34760167ff79b2ceb0db9de92c159
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: my-sqlpad-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: my-sqlpad
