apiVersion: v1
kind: Namespace
metadata:
  name: sqlpad
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlpad
  namespace: sqlpad
  labels:
    app: sqlpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlpad
  template:
    metadata:
      labels:
        app: sqlpad
    spec:             
      containers:
      - name: sqlpad
        image: sqlpad/sqlpad:5
        ports:
        - containerPort: 3001
        env:
          - name: SQLPAD_ADMIN
            value: "admin@sqlpad.com"
          - name: SQLPAD_ADMIN_PASSWORD
            value: "admin"
          - name: SQLPAD_APP_LOG_LEVEL
            value: 'debug'
          - name: SQLPAD_WEB_LOG_LEVEL
            value: 'warn'
          - name: SQLPAD_CONNECTIONS__pgdemo__name
            value: 'Postgres demo'
          - name: SQLPAD_CONNECTIONS__pgdemo__driver
            value: 'postgres'
          - name: SQLPAD_CONNECTIONS__pgdemo__host
            value: 'localhost'
          - name: SQLPAD_CONNECTIONS__pgdemo__database
            value: 'sqlpad'
          - name: SQLPAD_CONNECTIONS__pgdemo__username
            value: 'sqlpad'
          - name: SQLPAD_CONNECTIONS__pgdemo__password
            value: 'sqlpad'
          - name: SQLPAD_CONNECTIONS__pgdemo__multiStatementTransactionEnabled
            value: 'true'    
          - name: SQLPAD_CONNECTIONS__pgdemo__idleTimeoutSeconds
            value: '86400'           
---
apiVersion: v1
kind: Service
metadata:
  name: sqlpad-svc
  namespace: sqlpad
spec:
  type: NodePort
  ports:
  - name: tcp-rule-sqlpad
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: sqlpad